import fs from 'node:fs';
import path from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {translate} from './locale.mjs';
const BASE=path.dirname(fileURLToPath(import.meta.url));
const KEYS=['tokens.css','components.html','DESIGN.md','references.json','settings.json'];
const hash=s=>createHash('sha256').update(s).digest('hex');
export function noLinks(file){let current=path.resolve(file);for(;;){try{if(fs.lstatSync(current).isSymbolicLink())throw new Error('拒绝符号链接路径')}catch(e){if(e.code!=='ENOENT')throw e}const parent=path.dirname(current);if(parent===current)break;current=parent}return path.resolve(file)}
function atomic(file,content){noLinks(file);noLinks(path.dirname(file));const tmp=file+'.'+randomUUID()+'.tmp';fs.writeFileSync(tmp,content,{flag:'wx',mode:0o600});fs.renameSync(tmp,file)}
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const unesc=s=>s.replaceAll('&quot;','"').replaceAll('&gt;','>').replaceAll('&lt;','<').replaceAll('&amp;','&');
function validatePlain(v,max=2000){if(typeof v!=='string'||v.length>max||/[\u0000-\u0008]/.test(v))throw new Error('文本格式或长度无效');return v}
function exactKeys(v,allowed){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!allowed.includes(k)))throw new Error('包含未知字段')}
export class DesignStore{
 constructor(root){this.root=noLinks(root);this.system=path.join(this.root,'design-system');this.log=[];this.closed=false;fs.mkdirSync(this.root,{recursive:true,mode:0o700});noLinks(this.root);this.lock=path.join(this.root,'.writer.lock');noLinks(this.lock);this.lockFd=fs.openSync(this.lock,'wx',0o600);fs.writeFileSync(this.lockFd,JSON.stringify({pid:process.pid,at:new Date().toISOString()}));try{this.initialize();this.recover();this.read();this.emit('工作区已载入',translate('真实磁盘')+' · '+this.root)}catch(e){this.close();throw e}}
 file(key){if(!KEYS.includes(key))throw new Error('文件不在允许列表');return noLinks(path.join(this.system,key))}
 initialize(){const marker=path.join(this.root,'project.json');noLinks(marker);if(fs.existsSync(marker)){if(JSON.parse(fs.readFileSync(marker)).schema!==1)throw new Error('项目格式不兼容');return}if(fs.existsSync(this.system))throw new Error('已有未托管设计系统，拒绝覆盖');fs.mkdirSync(this.system);fs.mkdirSync(path.join(this.root,'revisions'));for(const d of ['preview','assets'])fs.mkdirSync(path.join(this.system,d));
 const refs=[{category:'design',title:'Google DESIGN.md',url:'https://github.com/google-labs-code/design.md',status:'预置官方来源，待项目适配'},{category:'system',title:'GitHub Primer',url:'https://primer.style/',status:'预置官方来源'},{category:'screen',title:'Lazyweb screens',url:'https://www.lazyweb.com/browse',status:'发现入口，不是已选具体 screen'},{category:'flow',title:'Lazyweb flows',url:'https://www.lazyweb.com/flow',status:'发现入口，不是已选具体 flow'},{category:'template',title:'Next.js & shadcn Dashboard',url:'https://vercel.com/templates/next.js/next-js-and-shadcn-ui-admin-dashboard',status:'模板候选；许可证与依赖待核验'}];
 fs.writeFileSync(this.file('tokens.css'),fs.readFileSync(path.join(BASE,'seed/tokens.css')));fs.writeFileSync(this.file('components.html'),translate(fs.readFileSync(path.join(BASE,'seed/components.html'),'utf8')));fs.writeFileSync(this.file('DESIGN.md'),translate('# 项目设计系统\n\n## 设计真源\ntokens.css 是数值唯一真源；components.html 是组件设计唯一真源。\n\n## 使用场景\n经营概览与 Agent 工作区。界面中的经营数据仅为演示数据。\n\n## 交互\n组件选中、标题编辑、网格/列表、主题与密度均使用明确的可编辑契约。\n\n## 参考\n预置来源是研究入口，不声称已完成在线调研；使用 Pi 的参考工作流补齐具体 screens/flows。\n\n## 主题\n主题选择保存到 settings.json，不另存一套 token 数值。\n\n## 组件\n按钮、表单、指标、进展与聊天组件共享真实 tokens。\n\n## 边界\n本地原型不是业务后端；不伪造登录、模型调用、构建或部署成功。\n'));fs.writeFileSync(this.file('references.json'),JSON.stringify(refs.map(r=>({...r,title:translate(r.title),status:translate(r.status)})),null,2));fs.writeFileSync(this.file('settings.json'),JSON.stringify({theme:'light',locks:[]},null,2));fs.writeFileSync(path.join(this.system,'manifest.json'),JSON.stringify({schemaVersion:'pi-design-studio/v1',id:'project',files:{tokens:'tokens.css',components:'components.html',design:'DESIGN.md'},previewDir:'preview',assetsDir:'assets'},null,2));fs.writeFileSync(path.join(this.system,'assets/SOURCES.md'),'# 资产\n原创 HTML/CSS，系统字体未打包；无第三方图像素材。经营数字为演示值。参考网址不授予品牌资产许可。\n');atomic(marker,JSON.stringify({schema:1,revision:0}));const values=this.values();this.snapshot(0,values,translate('初始化'));this.derive(values)}
 values(){return Object.fromEntries(KEYS.map(k=>{const p=this.file(k);const s=fs.statSync(p);if(!s.isFile()||s.size>1000000)throw new Error('文件类型或体积无效');return[k,fs.readFileSync(p,'utf8')]}))}
 emit(title,detail=''){this.log.push({at:new Date().toISOString(),title:translate(title),detail:detail.slice(0,300)});if(this.log.length>70)this.log.shift()}
 snapshot(revision,values,label){const p=noLinks(path.join(this.root,'revisions',revision+'.json'));if(fs.existsSync(p))throw new Error('版本已存在');atomic(p,JSON.stringify({revision,label,at:new Date().toISOString(),values},null,2))}
 recover(){const file=noLinks(path.join(this.root,'transaction.json'));if(!fs.existsSync(file))return;const data=JSON.parse(fs.readFileSync(file));if(!data.before||!Number.isSafeInteger(data.revision))throw new Error('恢复日志无效，请人工检查');for(const k of KEYS){if(typeof data.before[k]!=='string')throw new Error('恢复数据无效');atomic(this.file(k),data.before[k])}atomic(path.join(this.root,'project.json'),JSON.stringify({schema:1,revision:data.revision}));fs.unlinkSync(file);this.derive(data.before);this.emit('未完成事务已恢复','保留孤立快照，不覆盖历史')}
 read(){if(this.closed)throw new Error('工作区已关闭');noLinks(path.join(this.root,'project.json'));const meta=JSON.parse(fs.readFileSync(path.join(this.root,'project.json')));const values=this.values();const css=values['tokens.css'];const token=(name)=>{const m=css.match(new RegExp('--'+name+'\\s*:\\s*([^;}]+)'));if(!m)throw new Error('缺少 token: '+name);return m[1].trim()};const match=values['components.html'].match(/<h1\b[^>]*\bid="headline"[^>]*>([^<]*)<\/h1>/);if(!match)throw new Error('组件需要纯文本 h1#headline 编辑契约');const settings=JSON.parse(values['settings.json']);if(!Array.isArray(settings.locks)||!['light','dark'].includes(settings.theme))throw new Error('配置无效');return{revision:meta.revision,etag:hash(JSON.stringify(values)),values,state:{accent:token('accent'),radius:parseInt(token('radius')),space:parseInt(token('space')),headline:unesc(match[1]),variant:values['components.html'].match(/data-variant="(grid|list)"/)?.[1]||'grid',theme:settings.theme,locks:settings.locks},references:JSON.parse(values['references.json']),history:fs.readdirSync(noLinks(path.join(this.root,'revisions'))).filter(f=>/^\d+\.json$/.test(f)).map(f=>JSON.parse(fs.readFileSync(noLinks(path.join(this.root,'revisions',f))))).map(({revision,label,at})=>({revision,label,at})).sort((a,b)=>b.revision-a.revision).slice(0,50),events:[...this.log],root:this.root}}
 apply(base,patch,label=translate('应用设计修改')){exactKeys(patch,['accent','radius','space','headline','variant','theme','locks','design','references']);const current=this.read();if(base!==current.etag)throw Object.assign(new Error('源文件已变化，请重新加载后合并；未覆盖任何文件'),{status:409});const values={...current.values};const settings=JSON.parse(values['settings.json']);if('headline' in patch&&settings.locks.includes('hero')&&patch.headline!==current.state.headline)throw new Error('标题已锁定；先单独解除锁定');for(const key of ['accent','radius','space'])if(key in patch){const v=patch[key];if(key==='accent'?typeof v!=='string'||!/^#[0-9a-f]{6}$/i.test(v):!Number.isInteger(v)||v<(key==='space'?8:0)||v>24)throw new Error('无效 token: '+key);const re=new RegExp('(--'+key+'\\s*:\\s*)[^;}]+');values['tokens.css']=values['tokens.css'].replace(re,(_m,prefix)=>prefix+v+(key==='accent'?'':'px'))}
 if('headline'in patch){validatePlain(patch.headline,80);if(!patch.headline.trim())throw new Error('标题不能为空');values['components.html']=values['components.html'].replace(/(<h1\b[^>]*\bid="headline"[^>]*>)[^<]*(<\/h1>)/,(_m,a,b)=>a+esc(patch.headline)+b)}if('variant'in patch){if(!['grid','list'].includes(patch.variant))throw new Error('无效布局');values['components.html']=values['components.html'].replace(/data-variant="(grid|list)"/,'data-variant="'+patch.variant+'"')}
 if('theme'in patch){if(!['light','dark'].includes(patch.theme))throw new Error('无效主题');settings.theme=patch.theme}if('locks'in patch){if(!Array.isArray(patch.locks)||patch.locks.length>1||patch.locks.some(v=>v!=='hero'))throw new Error('无效锁定');settings.locks=patch.locks}values['settings.json']=JSON.stringify(settings,null,2);if('design'in patch)values['DESIGN.md']=validatePlain(patch.design,50000);if('references'in patch){if(!Array.isArray(patch.references)||patch.references.length>20)throw new Error('参考数量无效');for(const r of patch.references){exactKeys(r,['category','title','url','status']);if(!['design','system','screen','flow','template'].includes(r.category))throw new Error('参考类别无效');validatePlain(r.title,150);validatePlain(r.status,300);const u=new URL(validatePlain(r.url,1000));if(u.protocol!=='https:'||u.username||u.password)throw new Error('参考 URL 必须是无凭据 HTTPS')}values['references.json']=JSON.stringify(patch.references,null,2)}return this.commit(current,values,label)}
 commit(current,values,label){if(this.read().etag!==current.etag)throw Object.assign(new Error('并发修改冲突'),{status:409});const max=this.read().history.reduce((a,b)=>Math.max(a,b.revision),current.revision);const next=max+1;if(next>500)throw new Error('达到 500 版上限，请归档项目');this.snapshot(next,values,label);const journal=noLinks(path.join(this.root,'transaction.json'));atomic(journal,JSON.stringify({revision:current.revision,before:current.values}));try{for(const k of KEYS)if(values[k]!==current.values[k])atomic(this.file(k),values[k]);this.derive(values);atomic(path.join(this.root,'project.json'),JSON.stringify({schema:1,revision:next}));fs.unlinkSync(journal)}catch(e){this.recover();throw e}this.emit('已写入版本 v'+next,label);return this.read()}
 restore(base,revision){if(!Number.isInteger(revision)||revision<0)throw new Error('无效版本');const current=this.read();if(base!==current.etag)throw Object.assign(new Error('版本冲突'),{status:409});const file=noLinks(path.join(this.root,'revisions',revision+'.json'));const target=JSON.parse(fs.readFileSync(file));if(current.state.locks.includes('hero'))throw new Error('先解除标题锁定再恢复历史版本');if(!target.values||KEYS.some(k=>typeof target.values[k]!=='string'))throw new Error('快照无效');return this.commit(current,target.values,'从 v'+revision+' 恢复；旧历史保留')}
 derive(values){const html=this.html(values);atomic(noLinks(path.join(this.system,'preview/index.html')),html)}
 html(values=this.values()){const settings=JSON.parse(values['settings.json']);return values['components.html'].replace('<link rel="stylesheet" href="tokens.css">','<style>'+values['tokens.css']+'</style>').replace(/(<html lang="(?:zh-CN|en-US)")>/,'$1 data-theme="'+settings.theme+'">')}
 exportFrontend(base){const current=this.read();if(base!==current.etag)throw Object.assign(new Error('版本冲突'),{status:409});const out=noLinks(path.join(this.root,'frontend-v'+current.revision));if(fs.existsSync(out))throw new Error('此版本前端已经导出；请修改并保存新版本再导出');fs.mkdirSync(out);const html=this.html(current.values).replace('</body>','<script>'+translate(fs.readFileSync(path.join(BASE,'public/prototype.js'),'utf8'))+'</script></body>');atomic(path.join(out,'index.html'),html);atomic(path.join(out,'tokens.css'),current.values['tokens.css']);atomic(path.join(out,'HANDOFF.md'),'# 可运行原生前端\n\n来自设计版本 v'+current.revision+'。原生 HTML/CSS/JS，不冒充 Next.js 模板转换。交互为本地任务与消息演示，无真实业务后端。\n\nVercel 模板工程化请通过 Pi 的前端工作流执行，核验许可证、依赖、路由、构建和视觉对照后交付。\n');const receipt={revision:current.revision,path:out,sha256:hash(html),kind:'native-html',frameworkBuild:'not-run',backend:'not-connected'};atomic(path.join(out,'receipt.json'),JSON.stringify(receipt,null,2));this.emit('可运行 HTML 已导出','v'+current.revision+' · '+receipt.sha256.slice(0,12));return {...receipt,html}}
 close(){if(this.closed)return;this.closed=true;if(this.lockFd!==undefined){fs.closeSync(this.lockFd);this.lockFd=undefined;try{fs.unlinkSync(this.lock)}catch{}}}
}
