import http from 'node:http';import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {DesignStore} from '../store.mjs';import {startStudio} from '../server.mjs';
function fixture(t){const root=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'design-real-'));const store=new DesignStore(root);t.after(()=>{store.close();fs.rmSync(root,{recursive:true,force:true})});return store}
test('六项文件、持久保存、派生预览一致',t=>{const s=fixture(t);for(const f of ['manifest.json','DESIGN.md','tokens.css','components.html','preview','assets'])assert.ok(fs.existsSync(path.join(s.system,f)));const a=s.read();const b=s.apply(a.etag,{accent:'#345b8a',radius:18,headline:'真实保存标题'});assert.equal(b.revision,1);assert.match(b.values['tokens.css'],/--radius:18px/);assert.match(b.values['components.html'],/真实保存标题/);assert.match(fs.readFileSync(path.join(s.system,'preview/index.html'),'utf8'),/--radius:18px/)});
test('主题选择不修改 token 文件',t=>{const s=fixture(t),a=s.read();const b=s.apply(a.etag,{theme:'dark'});assert.equal(b.values['tokens.css'],a.values['tokens.css']);assert.equal(b.state.theme,'dark')});
test('版本冲突拒绝覆盖',t=>{const s=fixture(t),a=s.read();s.apply(a.etag,{radius:18});assert.throws(()=>s.apply(a.etag,{radius:20}),/源文件已变化/);assert.equal(s.read().state.radius,18)});
test('外部修改检测',t=>{const s=fixture(t),a=s.read();fs.appendFileSync(s.file('DESIGN.md'),'\n外部修改');assert.throws(()=>s.apply(a.etag,{radius:20}),/源文件已变化/)});
test('锁定服务端执行，不能同请求解锁后改标题',t=>{const s=fixture(t);let a=s.read();a=s.apply(a.etag,{locks:['hero']});assert.throws(()=>s.apply(a.etag,{locks:[],headline:'绕过'}),/已锁定/);assert.throws(()=>s.restore(a.etag,0),/解除标题锁定/);a=s.apply(a.etag,{locks:[]});assert.equal(s.apply(a.etag,{headline:'可修改'}).state.headline,'可修改')});
test('标题转义防止注入',t=>{const s=fixture(t),a=s.read();const b=s.apply(a.etag,{headline:'<script>alert(1)</script>'});assert.match(b.values['components.html'],/&lt;script&gt;/);assert.equal(b.state.headline,'<script>alert(1)</script>')});
test('历史恢复创建新版本，旧版保留',t=>{const s=fixture(t);const b=s.apply(s.read().etag,{radius:20});const c=s.restore(b.etag,0);assert.equal(c.revision,2);assert.equal(c.state.radius,12);assert.equal(c.history.length,3)});
test('未知属性、非法 token、参考凭据拒绝',t=>{const s=fixture(t),a=s.read();for(const patch of [{other:'x'},{accent:'url(https://evil)'},{radius:999},{references:[{category:'design',title:'x',url:'https://u:p@example.com',status:'x'}]}])assert.throws(()=>s.apply(a.etag,patch));assert.equal(s.read().revision,0)});
test('同工作区拒绝第二个写入进程',t=>{const s=fixture(t);assert.throws(()=>new DesignStore(s.root),/EEXIST/)});
test('符号链接文件拒绝',t=>{const s=fixture(t);const target=path.join(s.root,'target');fs.writeFileSync(target,'private');fs.unlinkSync(s.file('tokens.css'));fs.symlinkSync(target,path.join(s.system,'tokens.css'));assert.throws(()=>s.read(),/符号链接/)});
test('事务崩溃日志恢复原版，不使用 JSON 作为正常数值真源',t=>{const s=fixture(t),a=s.read();fs.writeFileSync(path.join(s.root,'transaction.json'),JSON.stringify({before:a.values,revision:0}));fs.writeFileSync(s.file('tokens.css'),a.values['tokens.css'].replace('--radius:12px','--radius:24px'));s.recover();assert.equal(s.read().state.radius,12);assert.equal(fs.existsSync(path.join(s.root,'transaction.json')),false)});
test('真实 HTML 导出、哈希回执、重复导出不覆盖',t=>{const s=fixture(t);const a=s.read();const r=s.exportFrontend(a.etag);assert.equal(r.kind,'native-html');assert.ok(fs.existsSync(path.join(r.path,'index.html')));assert.match(r.html,/chat-form/);assert.equal(r.frameworkBuild,'not-run');assert.throws(()=>s.exportFrontend(a.etag),/已经导出/)});
test('HTTP 授权、Origin、Host、请求类型、跨路径边界',async t=>{const root=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'design-http-'));const app=await startStudio({root});t.after(async()=>{await app.close();fs.rmSync(root,{recursive:true,force:true})});assert.equal((await fetch(app.origin+'/api/state')).status,401);const headers={'X-Design-Key':app.token};assert.equal((await fetch(app.origin+'/api/state',{headers})).status,200);assert.equal((await fetch(app.origin+'/api/state',{headers:{...headers,Origin:'https://evil.invalid'}})).status,403);assert.equal(await new Promise((resolve,reject)=>{const req=http.get(app.origin+'/api/state',{headers:{...headers,Host:'evil.invalid'}},res=>{res.resume();resolve(res.statusCode)});req.on('error',reject)}),403);assert.equal((await fetch(app.origin+'/etc/passwd')).status,404);assert.equal((await fetch(app.origin+'/api/apply',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:'{}'})).status,403);assert.equal((await fetch(app.origin+'/api/prompt',{method:'POST',headers:{...headers,Origin:app.origin,'Content-Type':'application/json'},body:JSON.stringify({task:'edit',text:'test'})})).status,503)});
test('同 etag 并行保存仅一个成功',async t=>{const root=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'design-cas-'));const app=await startStudio({root});t.after(async()=>{await app.close();fs.rmSync(root,{recursive:true,force:true})});const base=app.store.read().etag;const req=radius=>fetch(app.origin+'/api/apply',{method:'POST',headers:{'X-Design-Key':app.token,Origin:app.origin,'Content-Type':'application/json'},body:JSON.stringify({base,patch:{radius}})});const results=await Promise.all([req(18),req(20)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409])});
